/**
 * version.ts — Runtime build identity (semver + optional commit/time).
 *
 * version.json is generated by scripts/stamp-version.mjs at build time.
 * When missing (e.g. raw vitest runs), falls back to package.json only.
 */

import { readFileSync } from "fs";
import { join } from "path";

export interface BuildInfo {
  version: string;
  builtAt?: string;
  commit?: string;
}

function readPackageVersion(): string {
  const pkgPath = join(__dirname, "..", "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version?: string };
  return pkg.version ?? "0.0.0";
}

function loadBuildInfo(): BuildInfo {
  try {
    const raw = readFileSync(join(__dirname, "version.json"), "utf8");
    const data = JSON.parse(raw) as BuildInfo;
    return {
      version: data.version ?? readPackageVersion(),
      builtAt: data.builtAt,
      commit: data.commit,
    };
  } catch {
    return { version: readPackageVersion() };
  }
}

export const BUILD_INFO: BuildInfo = loadBuildInfo();
